baseURL = 'https://hugo.ropelab.uber.space/'
languageCode = 'de'
title = 'Social Rope Lab'
# hugo_cache = '/home/ropelab/tmp'
# publishDir = '/var/www/virtual/ropelab/hugo.ropelab.uber.space'
hugo_cache = './tmp'
publishDir = './result'
